### ISSUE TITLE
Group Creation not updating Realtime

### ISSUE THREAD

**Issue by niteshorntech** [cometchat-pro/android-kotlin-chat-app#8]
Once the Group is formed, it does not immediately come up in the Groups list. You have to click Groups to see the recently created Group: this is not updating realtime, because when we click on the group again this is showing the new group

**Comment by darshanbhanushali** [comment]
Hi @niteshorntech ,

You will not receive real-time events for Group Creation as it is not available yet. But you will receive an event when you are a member of a group. For example:- If someone adds you in a group then you will receive real-time action message with action "added". Similarly, you can receive other real-time events like **kicked, banned, unbanned & joined.**

Thank you for reporting the issue we have created a feature request please visit the above link to track the request. 
https://feedback.cometchat.com/cometchat-pro-feature-requests/p/send-a-real-time-event-when-someone-creates-a-group-via-dashboard-or-api

**Comment by niteshorntech** [comment]
This is a general feature

when we create any group in any kind of app this shows us when we end up creating. but the same is not happening with the CC

**Comment by darshanbhanushali** [comment]
Hi @niteshorntech ,

In sample app whenever you create a group it takes you to the chat screen of the group. That means you joined the group and can send a message in a group. If you want to get the newly created group in your group-list then instead of sending it to chat screen you need to call `fetchNext()` of `GroupRequest` again in the `onSuccess()` of create group.  In this way, you will get the new group in a group-list.

You can refer the  below documentation link to create a group
https://prodocs.cometchat.com/docs/android-groups-create-group
